import 'package:get/get.dart';

class MyTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'hello': 'Hello',
      'dark_mode': 'Dark Mode',
      'share':'Share',
      "history_movie": "History Movie",
      "category": "Category",
      "search": "Search",
      "favourite": "Favourite",
      "profile": "Profile",
      'home': 'Home',
      'director': 'Director',
      'year': 'Year',
      'types': 'Types',
      'enter_movie_to_search': 'Enter the movie you want to search',
      'new_member': 'New Member',
      'not_logged_in': 'You are not logged in!',
      'login': 'Login',
      'setting': 'Setting',
      'privacy_policy': 'Privacy Policy',
      'rate': 'Rate',
      'logout': 'Logout',
      'enjoy_movies': 'Enjoy watching movies, everyone!',
      'watch_anytime': 'Watch movies online anytime, anywhere',
      'no_favourite_movies': 'No favourite movies yet!',
      'enter_question': 'Enter a question',
      'create_account': 'Create an Account',
      'register_details': 'Please fill in the details to register',
      'user_name': 'User Name',
      'password': 'Password',
      'confirm_password': 'Confirm Password',
      'sign_up': 'Sign Up',
      'already_have_account': 'Already have an account?',
      'dont_have_account': 'Don\'t have an account?',
      'login_prompt': 'Please login to your account',
      'welcome_back': 'Welcome Back!',
      'rate_movie': 'How do you feel about this movie?',
      'maybe_later': 'Maybe later',
      'war': 'War',
      'character': 'Character',
      'legend': 'Legend',
      'life': 'Life',
      'document': 'Document',
      "new_movies": "New Movies",
      "random_movies": "Random Movies"

    },
    'vi_VN': {
      'hello': 'Xin chào',
      'dark_mode': 'Chế độ tối',
      'share':'Chia sẻ',
      "history_movie": "Phim Lịch Sử",
      "category": "Thể Loại",
      'home': 'Trang chủ',
      'search': 'Tìm kiếm',
      'favourite': 'Yêu thích',
      'profile': 'Hồ sơ',
      'director': 'Đạo diễn',
      'year': 'Năm',
      'types': 'Thể loại',
      'enter_movie_to_search': 'Nhập phim bạn muốn tìm',
      'new_member': 'Thành viên mới',
      'not_logged_in': 'Bạn chưa đăng nhập!',
      'login': 'Đăng nhập',
      'setting': 'Cài đặt',
      'privacy_policy': 'Chính sách bảo mật',
      'rate': 'Đánh giá',
      'logout': 'Đăng xuất',
      'enjoy_movies': 'Chúc mọi người xem phim vui vẻ',
      'watch_anytime': 'Xem phim online mọi lúc mọi nơi',
      'no_favourite_movies': 'Chưa có bộ phim yêu thích nào!',
      'enter_question': 'Nhập câu hỏi',
      'create_account': 'Tạo tài khoản',
      'register_details': 'Vui lòng điền thông tin để đăng ký',
      'user_name': 'Tên người dùng',
      'password': 'Mật khẩu',
      'confirm_password': 'Xác nhận mật khẩu',
      'sign_up': 'Đăng ký',
      'already_have_account': 'Đã có tài khoản?',
      'dont_have_account': 'Chưa có tài khoản?',
      'login_prompt': 'Vui lòng đăng nhập tài khoản của bạn',
      'welcome_back': 'Chào mừng trở lại!',
      'rate_movie': 'Bạn thấy phim này như thế nào?',
      'maybe_later': 'Để sau',
      'war': 'Chiến tranh',
      'character': 'Nhân vật',
      'legend': 'Truyền thuyết',
      'life': 'Đời sống',
      'document': 'Tư liệu',
      "new_movies": "Phim mới",
      "random_movies": "Phim ngẫu nhiên"
    },
  };
}
